package com.liujunbo.springbootdemo.entity;

public class TScore {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_score.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_score.c_score
     *
     * @mbggenerated
     */
    private String cScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_score.c_project_code
     *
     * @mbggenerated
     */
    private String cProjectCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_score.c_project_name
     *
     * @mbggenerated
     */
    private String cProjectName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_score.c_sid
     *
     * @mbggenerated
     */
    private Integer cSid;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_score
     *
     * @mbggenerated
     */
    public TScore(Integer id, String cScore, String cProjectCode, String cProjectName, Integer cSid) {
        this.id = id;
        this.cScore = cScore;
        this.cProjectCode = cProjectCode;
        this.cProjectName = cProjectName;
        this.cSid = cSid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_score
     *
     * @mbggenerated
     */
    public TScore() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_score.id
     *
     * @return the value of t_score.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_score.id
     *
     * @param id the value for t_score.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_score.c_score
     *
     * @return the value of t_score.c_score
     *
     * @mbggenerated
     */
    public String getcScore() {
        return cScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_score.c_score
     *
     * @param cScore the value for t_score.c_score
     *
     * @mbggenerated
     */
    public void setcScore(String cScore) {
        this.cScore = cScore == null ? null : cScore.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_score.c_project_code
     *
     * @return the value of t_score.c_project_code
     *
     * @mbggenerated
     */
    public String getcProjectCode() {
        return cProjectCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_score.c_project_code
     *
     * @param cProjectCode the value for t_score.c_project_code
     *
     * @mbggenerated
     */
    public void setcProjectCode(String cProjectCode) {
        this.cProjectCode = cProjectCode == null ? null : cProjectCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_score.c_project_name
     *
     * @return the value of t_score.c_project_name
     *
     * @mbggenerated
     */
    public String getcProjectName() {
        return cProjectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_score.c_project_name
     *
     * @param cProjectName the value for t_score.c_project_name
     *
     * @mbggenerated
     */
    public void setcProjectName(String cProjectName) {
        this.cProjectName = cProjectName == null ? null : cProjectName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_score.c_sid
     *
     * @return the value of t_score.c_sid
     *
     * @mbggenerated
     */
    public Integer getcSid() {
        return cSid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_score.c_sid
     *
     * @param cSid the value for t_score.c_sid
     *
     * @mbggenerated
     */
    public void setcSid(Integer cSid) {
        this.cSid = cSid;
    }
}