package com.liujunbo.springbootdemo.entity;

public class TStudent {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.s_name
     *
     * @mbggenerated
     */
    private String sName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.s_no
     *
     * @mbggenerated
     */
    private String sNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.s_sex
     *
     * @mbggenerated
     */
    private Integer sSex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.s_age
     *
     * @mbggenerated
     */
    private Integer sAge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.s_address
     *
     * @mbggenerated
     */
    private String sAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.s_keeper
     *
     * @mbggenerated
     */
    private String sKeeper;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.s_keeper_phone
     *
     * @mbggenerated
     */
    private String sKeeperPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.s_class_code
     *
     * @mbggenerated
     */
    private String sClassCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.s_class_name
     *
     * @mbggenerated
     */
    private String sClassName;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student
     *
     * @mbggenerated
     */
    public TStudent(Integer id, String sName, String sNo, Integer sSex, Integer sAge, String sAddress, String sKeeper, String sKeeperPhone, String sClassCode, String sClassName) {
        this.id = id;
        this.sName = sName;
        this.sNo = sNo;
        this.sSex = sSex;
        this.sAge = sAge;
        this.sAddress = sAddress;
        this.sKeeper = sKeeper;
        this.sKeeperPhone = sKeeperPhone;
        this.sClassCode = sClassCode;
        this.sClassName = sClassName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student
     *
     * @mbggenerated
     */
    public TStudent() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.id
     *
     * @return the value of t_student.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.id
     *
     * @param id the value for t_student.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.s_name
     *
     * @return the value of t_student.s_name
     *
     * @mbggenerated
     */
    public String getsName() {
        return sName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.s_name
     *
     * @param sName the value for t_student.s_name
     *
     * @mbggenerated
     */
    public void setsName(String sName) {
        this.sName = sName == null ? null : sName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.s_no
     *
     * @return the value of t_student.s_no
     *
     * @mbggenerated
     */
    public String getsNo() {
        return sNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.s_no
     *
     * @param sNo the value for t_student.s_no
     *
     * @mbggenerated
     */
    public void setsNo(String sNo) {
        this.sNo = sNo == null ? null : sNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.s_sex
     *
     * @return the value of t_student.s_sex
     *
     * @mbggenerated
     */
    public Integer getsSex() {
        return sSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.s_sex
     *
     * @param sSex the value for t_student.s_sex
     *
     * @mbggenerated
     */
    public void setsSex(Integer sSex) {
        this.sSex = sSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.s_age
     *
     * @return the value of t_student.s_age
     *
     * @mbggenerated
     */
    public Integer getsAge() {
        return sAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.s_age
     *
     * @param sAge the value for t_student.s_age
     *
     * @mbggenerated
     */
    public void setsAge(Integer sAge) {
        this.sAge = sAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.s_address
     *
     * @return the value of t_student.s_address
     *
     * @mbggenerated
     */
    public String getsAddress() {
        return sAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.s_address
     *
     * @param sAddress the value for t_student.s_address
     *
     * @mbggenerated
     */
    public void setsAddress(String sAddress) {
        this.sAddress = sAddress == null ? null : sAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.s_keeper
     *
     * @return the value of t_student.s_keeper
     *
     * @mbggenerated
     */
    public String getsKeeper() {
        return sKeeper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.s_keeper
     *
     * @param sKeeper the value for t_student.s_keeper
     *
     * @mbggenerated
     */
    public void setsKeeper(String sKeeper) {
        this.sKeeper = sKeeper == null ? null : sKeeper.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.s_keeper_phone
     *
     * @return the value of t_student.s_keeper_phone
     *
     * @mbggenerated
     */
    public String getsKeeperPhone() {
        return sKeeperPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.s_keeper_phone
     *
     * @param sKeeperPhone the value for t_student.s_keeper_phone
     *
     * @mbggenerated
     */
    public void setsKeeperPhone(String sKeeperPhone) {
        this.sKeeperPhone = sKeeperPhone == null ? null : sKeeperPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.s_class_code
     *
     * @return the value of t_student.s_class_code
     *
     * @mbggenerated
     */
    public String getsClassCode() {
        return sClassCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.s_class_code
     *
     * @param sClassCode the value for t_student.s_class_code
     *
     * @mbggenerated
     */
    public void setsClassCode(String sClassCode) {
        this.sClassCode = sClassCode == null ? null : sClassCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.s_class_name
     *
     * @return the value of t_student.s_class_name
     *
     * @mbggenerated
     */
    public String getsClassName() {
        return sClassName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.s_class_name
     *
     * @param sClassName the value for t_student.s_class_name
     *
     * @mbggenerated
     */
    public void setsClassName(String sClassName) {
        this.sClassName = sClassName == null ? null : sClassName.trim();
    }
}