package com.liujunbo.springbootdemo.dao;

import com.liujunbo.springbootdemo.entity.TSchool;

public interface TSchoolMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_school
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_school
     *
     * @mbggenerated
     */
    int insert(TSchool record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_school
     *
     * @mbggenerated
     */
    int insertSelective(TSchool record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_school
     *
     * @mbggenerated
     */
    TSchool selectByPrimaryKey(Integer id);



    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_school
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TSchool record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_school
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TSchool record);
}