package com.liujunbo.springbootdemo.dao;

import com.liujunbo.springbootdemo.entity.TScore;

public interface TScoreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_score
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_score
     *
     * @mbggenerated
     */
    int insert(TScore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_score
     *
     * @mbggenerated
     */
    int insertSelective(TScore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_score
     *
     * @mbggenerated
     */
    TScore selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_score
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TScore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_score
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TScore record);
}